In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [2]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [3]:
import seaborn as sns

In [4]:
iris = sns.load_dataset('iris')

In [5]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
knn = KNeighborsClassifier()

In [8]:
knn.fit(iris.iloc[:,:-1], iris.species)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [9]:
knn.predict([[3,3,3,3]])

array(['versicolor'], dtype=object)

In [ ]:
# tensorflow에서는 모든 데이터가 숫자여야 함 # 문자열 불가

In [10]:
import pandas as pd

In [11]:
ohe = pd.get_dummies(iris.species) # OneHotEncoding

In [12]:
iris  = pd.concat([iris,ohe], axis=1)

In [14]:
iris.drop(columns='species', inplace=True)

In [16]:
knn2 = KNeighborsClassifier()

In [17]:
knn2.fit(iris.iloc[:,:-3], iris.iloc[:,-3:])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [18]:
knn2.predict([[3,3,3,3]]) # 자동으로 ohe

array([[0, 1, 0]], dtype=uint8)

In [19]:
knn2.predict_proba([[3,3,3,3]]) # 확률로도 구할 수 있음

[array([[1., 0.]]), array([[0.2, 0.8]]), array([[0.8, 0.2]])]

In [ ]:
# 사이킷런은 타켓값을 총 세 개 # 문자열, ohe, 라벨 인ㅋ코딩

In [20]:
import tensorflow as tf

In [22]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(16, input_shape=(4,), activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
    ]
)

In [ ]:
# model을 만들 때, add와 pop

In [ ]:
# tf.keras.activations.relu # function 또는 class # -> 기본값을 바꿀 수 있다
# tf.nn.relu

In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                80        
_________________________________________________________________
dense_1 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
Total params: 403
Trainable params: 403
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 학습전략 complie

In [ ]:
tf.keras.losses. # 문자로 집어넣으면 디폴트, 객체나 값을 갖다쓰면 내가 바꿀 수 있음

In [ ]:
tf.keras.optimizers.

In [24]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [26]:
# numpy 필요 없이 바로 pandas 데이터를 쓸 수 있음

model.fit(iris.iloc[:,:-3], iris.iloc[:,-3:], epochs=5) # epochs은 누적됨 # 하면 할수록 loss는 떨어지고 accuracy는 오름
# 그러나 overfitting이 될 수도 있음 # 또한, test data가 커진다

Epoch 1/5
5/5 [==============================] - 0s 1ms/step - loss: 1.6467 - accuracy: 0.3333
Epoch 2/5
5/5 [==============================] - 0s 1ms/step - loss: 1.4273 - accuracy: 0.3333
Epoch 3/5
5/5 [==============================] - 0s 2ms/step - loss: 1.2498 - accuracy: 0.3333
Epoch 4/5
5/5 [==============================] - 0s 1ms/step - loss: 1.1132 - accuracy: 0.3400
Epoch 5/5
5/5 [==============================] - 0s 2ms/step - loss: 1.0101 - accuracy: 0.4333


In [ ]:
# 스파스와 스파스 아닐 때 # ohe이 안 되어있으면 스파스 해야 됨 # 돼있으면 스파스 떼야 됨

In [ ]:
# 최종적으로 pandas와 바로 연동됨을 확인할 수 있다

In [27]:
def build_fn():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(16, input_shape=(4,), activation='relu'),
        tf.keras.layers.Dense(16, activation='relu'),
        tf.keras.layers.Dense(3, activation='softmax')
        ]
    )
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [28]:
kc = KerasClassifier() # (build_fn=None, **sk_params) # 인자를 쓰려면, 디폴트 테크닉을 써야 한다

AttributeError: 'KerasClassifier' object has no attribute '__call__'

In [29]:
kc = KerasClassifier(build_fn) # 오류 해결

In [30]:
kc.fit(iris.iloc[:,:-3], iris.iloc[:,-3:])

5/5 [==============================] - 0s 1ms/step - loss: 0.9528 - accuracy: 0.6667


In [ ]:
# 사이킷의 기능을 GPU를 써서 사용할 수 있음 # 근데 epochs이 1회만 돌아감

In [32]:
kc.fit(iris.iloc[:,:-3], iris.iloc[:,-3:], epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 1.3507 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 1.2418 - accuracy: 0.5200
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 1.1600 - accuracy: 0.6667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 1.0890 - accuracy: 0.6667
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 1.0316 - accuracy: 0.6667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.9858 - accuracy: 0.6667
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 0.9487 - accuracy: 0.6667
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.9159 - accuracy: 0.6667
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8863 - accuracy: 0.6667
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8581 - accuracy: 0.6667


In [40]:
from sklearn.model_selection import cross_val_score, learning_curve

In [38]:
kc = KerasClassifier(build_fn, epochs=10) # 여기에다 epochs을

In [39]:
cross_val_score(kc, iris.iloc[:,:-3], iris.iloc[:,-3:], cv=10)

Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 1.8229 - accuracy: 0.2593
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 1.5456 - accuracy: 0.2519
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 1.3607 - accuracy: 0.4370
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 1.2193 - accuracy: 0.6000
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 1.1254 - accuracy: 0.4667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 1.0630 - accuracy: 0.3630
Epoch 7/10
5/5 [==============================] - 0s 997us/step - loss: 1.0229 - accuracy: 0.3926
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.9966 - accuracy: 0.3630
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.9808 - accuracy: 0.4222
Epoch 10/10
1/1 [==============================] - 0s 997us/step - loss: 1.1998 - accuracy: 0.0000e+00
Epoch 1/10
5/5 [===============

5/5 [==============================] - 0s 2ms/step - loss: 1.1226 - accuracy: 0.3630
Epoch 10/10
1/1 [==============================] - 0s 976us/step - loss: 1.1303 - accuracy: 0.0000e+00
Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 1.3329 - accuracy: 0.3704
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 1.2230 - accuracy: 0.3704
Epoch 3/10
5/5 [==============================] - 0s 996us/step - loss: 1.1475 - accuracy: 0.3704
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 1.0945 - accuracy: 0.4593
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 1.0560 - accuracy: 0.7259
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 1.0260 - accuracy: 0.7407
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 1.0013 - accuracy: 0.7407
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.9797 - accuracy: 0.7407
Epoch 9/10
5/5 [==========================

array([0.        , 0.46666667, 1.        , 0.46666667, 0.        ,
       0.        , 0.33333334, 0.        , 0.        , 0.2       ])

In [41]:
learning_curve(kc, iris.iloc[:,:-3], iris.iloc[:,-3:], cv=10)

Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4965 - accuracy: 1.0000
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 0.4655 - accuracy: 1.0000
Epoch 3/10
1/1 [==============================] - 0s 996us/step - loss: 0.4357 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4073 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 0.3803 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 994us/step - loss: 0.3547 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 0.3303 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 990us/step - loss: 0.3073 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 0.2855 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 0.2459 - accuracy: 1.0000
Epoch 1/10
2/2 [=================

3/3 [==============================] - 0s 1ms/step - loss: 1.5688 - accuracy: 0.0000e+00
Epoch 3/10
3/3 [==============================] - 0s 2ms/step - loss: 1.4350 - accuracy: 0.0000e+00
Epoch 4/10
3/3 [==============================] - 0s 2ms/step - loss: 1.3138 - accuracy: 0.0000e+00
Epoch 5/10
3/3 [==============================] - 0s 2ms/step - loss: 1.2061 - accuracy: 0.0541
Epoch 6/10
3/3 [==============================] - 0s 2ms/step - loss: 1.1066 - accuracy: 0.4324
Epoch 7/10
3/3 [==============================] - 0s 1ms/step - loss: 1.0142 - accuracy: 0.4730
Epoch 8/10
3/3 [==============================] - 0s 2ms/step - loss: 0.9343 - accuracy: 0.4730
Epoch 9/10
3/3 [==============================] - 0s 996us/step - loss: 0.8678 - accuracy: 0.6081
Epoch 10/10
3/3 [==============================] - 0s 997us/step - loss: 0.7651 - accuracy: 1.0000
Epoch 1/10
4/4 [==============================] - 0s 1ms/step - loss: 2.6238 - accuracy: 0.0769
Epoch 2/10
4/4 [==================

Epoch 4/10
5/5 [==============================] - 0s 997us/step - loss: 0.8275 - accuracy: 0.4074
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.7606 - accuracy: 0.5852
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.6997 - accuracy: 0.7852
Epoch 7/10
5/5 [==============================] - 0s 996us/step - loss: 0.6536 - accuracy: 0.9407
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.6166 - accuracy: 0.9778
Epoch 9/10
5/5 [==============================] - 0s 996us/step - loss: 0.5793 - accuracy: 0.9556
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.5370 - accuracy: 0.8519
Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 1.2033 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 1.1441 - accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 1.0865 - accuracy: 0.0000e+00
Epoch 4/10
1/1 [=====

2/2 [==============================] - 0s 2ms/step - loss: 0.4867 - accuracy: 1.0000
Epoch 6/10
2/2 [==============================] - 0s 2ms/step - loss: 0.4350 - accuracy: 1.0000
Epoch 7/10
2/2 [==============================] - 0s 2ms/step - loss: 0.3884 - accuracy: 1.0000
Epoch 8/10
2/2 [==============================] - 0s 1ms/step - loss: 0.3466 - accuracy: 1.0000
Epoch 9/10
2/2 [==============================] - 0s 2ms/step - loss: 0.3093 - accuracy: 1.0000
Epoch 10/10
2/2 [==============================] - 0s 1ms/step - loss: 0.2497 - accuracy: 1.0000
Epoch 1/10
3/3 [==============================] - 0s 997us/step - loss: 0.7325 - accuracy: 0.6757
Epoch 2/10
3/3 [==============================] - 0s 1ms/step - loss: 0.6722 - accuracy: 0.6757
Epoch 3/10
3/3 [==============================] - 0s 1ms/step - loss: 0.6243 - accuracy: 0.6757
Epoch 4/10
3/3 [==============================] - 0s 1ms/step - loss: 0.5787 - accuracy: 0.6757
Epoch 5/10
3/3 [==============================] 

4/4 [==============================] - 0s 1ms/step - loss: 0.6977 - accuracy: 0.9327
Epoch 8/10
4/4 [==============================] - 0s 1ms/step - loss: 0.6711 - accuracy: 0.9615
Epoch 9/10
4/4 [==============================] - 0s 1ms/step - loss: 0.6468 - accuracy: 0.9519
Epoch 10/10
4/4 [==============================] - 0s 997us/step - loss: 0.6082 - accuracy: 0.9519
Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 1.0685 - accuracy: 0.3704
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.9627 - accuracy: 0.3778
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8956 - accuracy: 0.4222
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.8345 - accuracy: 0.7037
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.7894 - accuracy: 0.7407
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.7562 - accuracy: 0.7407
Epoch 7/10
5/5 [==============================] 

1/1 [==============================] - 0s 996us/step - loss: 3.6224 - accuracy: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 3.5419 - accuracy: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 3.3884 - accuracy: 0.0000e+00
Epoch 1/10
2/2 [==============================] - 0s 1ms/step - loss: 2.3925 - accuracy: 0.0000e+00
Epoch 2/10
2/2 [==============================] - 0s 997us/step - loss: 2.2076 - accuracy: 0.0000e+00
Epoch 3/10
2/2 [==============================] - 0s 1ms/step - loss: 2.0248 - accuracy: 0.0000e+00
Epoch 4/10
2/2 [==============================] - 0s 1ms/step - loss: 1.8473 - accuracy: 0.0000e+00
Epoch 5/10
2/2 [==============================] - 0s 1ms/step - loss: 1.6787 - accuracy: 0.0000e+00
Epoch 6/10
2/2 [==============================] - 0s 2ms/step - loss: 1.5202 - accuracy: 0.0000e+00
Epoch 7/10
2/2 [==============================] - 0s 1ms/step - loss: 1.3705 - accuracy: 0.0000e+00
Epoch 

3/3 [==============================] - 0s 1ms/step - loss: 1.2935 - accuracy: 0.3243
Epoch 10/10
3/3 [==============================] - 0s 1ms/step - loss: 1.1283 - accuracy: 0.3243
Epoch 1/10
4/4 [==============================] - 0s 1ms/step - loss: 1.3192 - accuracy: 0.4808
Epoch 2/10
4/4 [==============================] - 0s 1ms/step - loss: 1.2101 - accuracy: 0.4808
Epoch 3/10
4/4 [==============================] - 0s 2ms/step - loss: 1.1154 - accuracy: 0.4808
Epoch 4/10
4/4 [==============================] - 0s 2ms/step - loss: 1.0393 - accuracy: 0.4808
Epoch 5/10
4/4 [==============================] - 0s 2ms/step - loss: 0.9694 - accuracy: 0.4808
Epoch 6/10
4/4 [==============================] - 0s 2ms/step - loss: 0.9195 - accuracy: 0.4808
Epoch 7/10
4/4 [==============================] - 0s 1ms/step - loss: 0.8868 - accuracy: 0.4808
Epoch 8/10
4/4 [==============================] - 0s 1ms/step - loss: 0.8540 - accuracy: 0.4808
Epoch 9/10
4/4 [==============================] - 

5/5 [==============================] - 0s 997us/step - loss: 0.9776 - accuracy: 0.3704


(array([ 13,  43,  74, 104, 135]),
 array([[1.        , 0.        , 1.        , 1.        , 0.        ,
         1.        , 1.        , 0.        , 0.        , 0.        ],
        [0.18604651, 0.18604651, 0.81395346, 1.        , 1.        ,
         1.        , 1.        , 0.86046511, 1.        , 1.        ],
        [0.52702701, 1.        , 0.52702701, 0.3918919 , 1.        ,
         0.82432431, 1.        , 0.67567569, 0.32432431, 0.98648649],
        [0.81730771, 0.1826923 , 0.33653846, 0.81730771, 0.81730771,
         0.95192307, 0.86538464, 0.96153843, 0.48076922, 0.96153843],
        [0.63703704, 0.47407407, 0.85185188, 0.7037037 , 0.32592592,
         0.74074072, 0.66666669, 0.86666667, 0.37037036, 0.37037036]]),
 array([[1.        , 0.        , 1.        , 1.        , 1.        ,
         0.        , 0.        , 1.        , 1.        , 1.        ],
        [0.        , 0.        , 1.        , 0.33333334, 0.        ,
         0.        , 0.33333334, 0.        , 0.        , 0. 

In [ ]:
# end-to-end # 성능, 유지보수 관리 용이

In [42]:
from tensorflow.keras.callbacks import Callback

In [ ]:
Callback. # 나오는 애들 오버라이딩 가능
Callback.on_epoch_begin

In [54]:
class MyCallback(Callback):
    def on_epoch_begin(self, epoch, logs=None):
        print(epoch, 'start!!!')

In [48]:
def build_fn():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(16, input_shape=(28*28,), activation='relu'),
        tf.keras.layers.Dense(16, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
        ]
    )
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [57]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

In [58]:
model = build_fn()

In [59]:
model.fit(X_train, y_train, epochs=5, callbacks=[MyCallback()])

0 start!!!
Epoch 1/5


ValueError: in user code:

    C:\Users\Shin\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    C:\Users\Shin\Anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Shin\Anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Shin\Anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Shin\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:531 train_step  **
        y_pred = self(x, training=True)
    C:\Users\Shin\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:886 __call__
        self.name)
    C:\Users\Shin\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:216 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer sequential_65 is incompatible with the layer: expected axis -1 of input shape to have value 784 but received input with shape [32, 28, 28]
