# NumPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [3]:
a = np.array([1, '1'])

In [4]:
a # 모두 문자로 바뀜 -> typecasting을 저절로 해준다 # 문자 데이터 관련 character array를 지원해준다

array(['1', '1'], dtype='<U11')

In [5]:
print(a)

['1' '1']


In [6]:
type(a)

numpy.ndarray

In [7]:
b = np.ndarray([1,2,])

In [8]:
b # 인스턴스화 해서도 만들 수 있다

array([[9.06811649e+036, 1.13092339e-208]])

In [9]:
aa = np.array([[1,2],[3]])

In [10]:
aa # 직사각형 형태가 아니면, 내부적으로 리스트로

array([list([1, 2]), list([3])], dtype=object)

In [11]:
aa = np.array([[1,2],[3,4]])

In [12]:
aa

array([[1, 2],
       [3, 4]])

In [13]:
aa = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [14]:
aa

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [15]:
aa.shape

(2, 2, 2)

In [16]:
aa.dtype

dtype('int32')

In [17]:
aa.ndim

3

In [18]:
aa.size # 원소의 개수

8

In [19]:
aa.itemsize # 32/8

4

In [20]:
aa = np.array([[[1,2],[3,4]],[[1,2],[3,4]]], dtype=float)

In [21]:
aa.itemsize # 64/8

8

In [22]:
aa.data # 하나의 연속된 배열로 데이터 저장 # 어떻게 몇 차원을 저장하지? -> stride

In [23]:
b = np.ones(3)

In [24]:
b

array([1., 1., 1.])

In [25]:
b = np.ones((3,4))

In [26]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
b = np.full((3,4),5)

In [28]:
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [29]:
c = np.ones_like(b) # b의 shape만 따와서 # _like: shape만 따온다

In [30]:
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
d = np.eye(4)

In [32]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
d = np.eye(4, k=1) # 1의 위치를 바꿔줌

In [34]:
d

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [35]:
e = np.identity(4) # eye와 달리 위치를 바꿀 수 없음, 무조건 단위행렬

In [36]:
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
f = np.diag([[1,2],[3,4]])

In [38]:
f

array([1, 4])

In [39]:
a = np.arange(10)

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = np.linspace(0, 10, num=10, endpoint=False)

In [42]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
dir(a) # '__getitem__', '__len__' -> 시퀀스 -> 인덱싱, 슬라이싱

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [44]:
a = np.arange(25).reshape(5,5)

In [45]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
a[0][1]

1

In [47]:
a[0,1] # ,로 차원 구분

1

In [48]:
a[0,:]

array([0, 1, 2, 3, 4])

In [49]:
a[0]

array([0, 1, 2, 3, 4])

In [50]:
b = np.arange(24).reshape(2,3,4)

In [51]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [52]:
b[1,1,2]

18

In [53]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
b[1,:,:]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
b[1,...] # 한 개 이상의 연속된 ':' == '...' # 맨 끝에 있는 ...은 생략 가능 -> b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
b[..., 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [57]:
b[:,:,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [58]:
...

Ellipsis

In [59]:
class B(int):
    def __add__(self,other):
        print('add')

In [60]:
x = B(3)

In [61]:
class B(int):
#     def __add__(self,other):
#         print('add')
    pass

In [62]:
x+x # 연산자 오버로딩

add


In [63]:
c = np.arange(25).reshape(5,5)

In [64]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
c[None,:], c[None,:].shape # 3차원

(array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]]]),
 (1, 5, 5))

In [66]:
c[:,None], c[:,None].shape # 3차원

(array([[[ 0,  1,  2,  3,  4]],
 
        [[ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14]],
 
        [[15, 16, 17, 18, 19]],
 
        [[20, 21, 22, 23, 24]]]),
 (5, 1, 5))

In [67]:
c[:,:,None], c[:,:,None].shape

(array([[[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4]],
 
        [[ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9]],
 
        [[10],
         [11],
         [12],
         [13],
         [14]],
 
        [[15],
         [16],
         [17],
         [18],
         [19]],
 
        [[20],
         [21],
         [22],
         [23],
         [24]]]),
 (5, 5, 1))

In [68]:
np.newaxis is None

True

In [69]:
c[np.newaxis]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [70]:
c > 10 # 내부적으로 broadcasting

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [71]:
a = [1,2,3]
b = [4,5,6]

In [72]:
a + b

[1, 2, 3, 4, 5, 6]

In [73]:
x = np.array(a)
y = np.array(b)

In [74]:
x + y # 같은 자리 원소끼리 더해주는 것 # element-wise

array([5, 7, 9])

In [75]:
c[c > 10] # boolean indexing

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
c[(c > 10) | (c < 5)]

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [77]:
c[(c > 10) & (c < 5)]

array([], dtype=int32)

In [78]:
x = np.ma.masked_array([1,2,],[True,False])

In [79]:
x

masked_array(data=[--, 2],
             mask=[ True, False],
       fill_value=999999)

In [80]:
d = np.mat([[1,2],[3,4]])

In [81]:
d

matrix([[1, 2],
        [3, 4]])

In [82]:
e = np.array([[1,2],[3,4]])

In [83]:
e

array([[1, 2],
       [3, 4]])

In [84]:
d*d

matrix([[ 7, 10],
        [15, 22]])

In [85]:
e*e

array([[ 1,  4],
       [ 9, 16]])

In [86]:
d@d

matrix([[ 7, 10],
        [15, 22]])

In [87]:
e@e # @: array에 대해서 행렬곱

array([[ 7, 10],
       [15, 22]])

In [88]:
np.multiply(e,e)

array([[ 1,  4],
       [ 9, 16]])

In [89]:
np.multiply(d,d)

matrix([[ 1,  4],
        [ 9, 16]])

In [90]:
np.dot(d,d)

matrix([[ 7, 10],
        [15, 22]])

In [91]:
d.dot(d)

matrix([[ 7, 10],
        [15, 22]])

In [92]:
from PIL import Image

In [94]:
x = Image.open('C://python_kr/sample_img.jpg')

In [95]:
dir(x) # '__array_interface__'

['_Image__transformer',
 '__array_interface__',
 '__class__',
 '__copy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_close_exclusive_fp_after_loading',
 '_copy',
 '_crop',
 '_dump',
 '_ensure_mutable',
 '_exclusive_fp',
 '_exif',
 '_expand',
 '_get_safe_box',
 '_getexif',
 '_getmp',
 '_min_frame',
 '_new',
 '_open',
 '_repr_png_',
 '_seek_check',
 '_size',
 'alpha_composite',
 'app',
 'applist',
 'bits',
 'category',
 'close',
 'convert',
 'copy',
 'crop',
 'custom_mimetype',
 'decoderconfig',
 'decodermaxblock',
 'draft',
 'effect_spread',
 'entropy',
 'filename',
 'filter',
 'format',
 'format_description',
 'fp'

In [96]:
y = np.array(x)

In [97]:
y

array([[[ 30,  82, 183],
        [ 27,  79, 180],
        [ 27,  79, 180],
        ...,
        [ 59, 121, 208],
        [ 60, 120, 208],
        [ 61, 121, 209]],

       [[ 26,  78, 179],
        [ 24,  76, 177],
        [ 27,  79, 180],
        ...,
        [ 61, 123, 210],
        [ 63, 123, 211],
        [ 63, 123, 211]],

       [[ 27,  79, 180],
        [ 26,  78, 179],
        [ 28,  80, 181],
        ...,
        [ 58, 120, 207],
        [ 62, 122, 210],
        [ 63, 123, 211]],

       ...,

       [[196, 180, 165],
        [194, 178, 165],
        [195, 179, 166],
        ...,
        [183, 170, 153],
        [182, 169, 152],
        [182, 169, 152]],

       [[194, 178, 163],
        [194, 178, 163],
        [196, 180, 167],
        ...,
        [183, 170, 153],
        [183, 170, 153],
        [182, 169, 152]],

       [[193, 177, 162],
        [195, 179, 164],
        [198, 182, 167],
        ...,
        [184, 171, 154],
        [184, 171, 154],
        [183, 170, 153]]

In [98]:
a = np.arange(25).reshape(5,5)

In [99]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
a[[0,1]] # 차원을 유지

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
a[0,1]

1

In [102]:
import seaborn as sns

In [103]:
tips = sns.load_dataset('tips')

In [104]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [105]:
tips['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ... 
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [106]:
tips[['day']]

day
0     Sun
1     Sun
2     Sun
3     Sun
4     Sun
..    ...
239   Sat
240   Sat
241   Sat
242   Sat
243  Thur

[244 rows x 1 columns]

In [107]:
tips[['sex','day']]

sex   day
0    Female   Sun
1      Male   Sun
2      Male   Sun
3      Male   Sun
4    Female   Sun
..      ...   ...
239    Male   Sat
240  Female   Sat
241    Male   Sat
242    Male   Sat
243  Female  Thur

[244 rows x 2 columns]

In [108]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [109]:
a[[1,0]] # 순서도 바꿀 수 있다

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [110]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
a[[0,1],[2,3]] # 0행 2열, 1행 3열

array([2, 8])

In [112]:
# (, , : , ...), (None, ), 조건(True, False), fancy indexing

#### Copy

In [113]:
a = b = [1,2,3]

In [114]:
a[0] = 100

In [115]:
b # mutable은 reference를 한다

[100, 2, 3]

In [116]:
x = np.array([1,2,3])

In [117]:
y = x

In [118]:
y[0] = 100

In [119]:
x

array([100,   2,   3])

In [120]:
a = [1,2,3]

In [121]:
b = a.copy()

In [122]:
a[0] = 100

In [123]:
b

[1, 2, 3]

In [124]:
a = [1,2,3]

In [125]:
b = a[:]

In [126]:
a[0] = 100

In [127]:
b

[1, 2, 3]

In [128]:
a = [[1,2],[3,4]]

In [129]:
b = a[:]

In [130]:
a[0][0] = 100

In [131]:
b

[[100, 2], [3, 4]]

In [132]:
a = [[1,2],[3,4]]

In [133]:
b = a.copy()

In [134]:
a[0][0] = 100

In [135]:
b

[[100, 2], [3, 4]]

In [136]:
import copy

In [137]:
a = [[1,2],[3,4]]

In [138]:
b = copy.deepcopy(a)

In [139]:
a[0][0] = 100

In [140]:
b

[[1, 2], [3, 4]]

In [141]:
# numpy의 copy == python의 deepcopy
# 그렇다면 python의 copy는? == numpy의 view

In [142]:
x = np.array([[1,2],[3,4]])

In [143]:
y = x.copy()

In [144]:
x[0][0] = 100

In [145]:
y

array([[1, 2],
       [3, 4]])

In [146]:
y = x.view()

In [147]:
x[0][0] = 100

In [148]:
y

array([[100,   2],
       [  3,   4]])